replicaCount: 1

image:
  repository: docker.io/elumole22/movies-app
  tag: 0b4481d
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

prometheus:
  enabled: true
  scrapePath: /metrics
  scrapePort: "8000"

env:
  DATABASE_URL: ""

resources: {}

labels:
  app: movies-app

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

externalSecrets:
  enabled: true
  secretStore:
    name: github-secret-store
    provider: github
  secret:
    name: movies-db-secret
    refreshInterval: 1h
  github:
    owner: oluwaTG
    repo: azure-devops-secrets
