{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ .Values.externalSecrets.namespace }}
spec:
  provider:
    github:
      owner: {{ .Values.externalSecrets.github.owner }}
      repo: {{ .Values.externalSecrets.github.repo }}
      auth:
        tokenRef:
          name: github-token
          key: token
{{- end }}
