postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 16.3.0-debian-12-r2
  auth:
    username: dev-movies
    password: movies
    database: movies

  primary:
    persistence:
      enabled: false
